[package]
name = "mesh-thumbnail-software"
version = "0.1.0"
edition = "2024"

[dependencies]
vek = "0"
image = { version = "0", features = ["png", "jpeg"] }
libmeshthumbnail = { path = "./libmeshthumbnail" }
clap = { version = "4.5.32", features = ["derive"] }

[profile.release]
strip = true
lto = true
codegen-units = 1